class Markers:
    TASK_START = "<task>"
    TASK_END = "</task>"
    ANS_START = "<answer>"
    ANS_END = "</answer>"
    CLARIFY_START = "<clarify>"
    CLARIFY_END = "</clarify>"
    TOOL_START = "<tool_call>"
    TOOL_END = "</tool_call>"
    THINK_START = "<think>"
    THINK_END = "</think>"
